dispatch:
    session:
        time: 3600
    tokenHeader: authorization
logging:
    level:
        cn.net.bhe.chargingsystem.manage: debug
mybatis:
    configuration:
        jdbc-type-for-null: 'null'
    mapper-locations: classpath*:mapper/*.xml, classpath*:mapper/**/*.xml
server:
    port: 8080
    servlet:
        session:
            timeout: 7200
spring:
    datasource:
        password: 20190627
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://www.bhe.net.cn:3306/charging_system
        username: keep
    devtools:
        restart:
            enabled: true
    redis:
        host: www.bhe.net.cn
        jedis:
            pool:
                max-active: 200
                max-idle: 50
                max-wait: -1
                min-idle: 0
        password: 20190627
        port: 6379
        timeout: 1000000
